name: Build Debug APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android-debug:
    name: Android Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Debug APK
        shell: bash
        run: |
          cd android
          ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-mobile-debug-${{ github.sha }}
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
